// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVP58lYJzfnjFGE-RKdSkrGgNJ3oMUncI',
    appId: '1:762160532123:android:e07d29ed89b36b30d1d43e',
    messagingSenderId: '762160532123',
    projectId: 'livegreen-bf838',
    databaseURL: 'https://livegreen-bf838-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'livegreen-bf838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfS0WH4Wac8Li0aA8ie_A4qge7UZtbVTc',
    appId: '1:762160532123:ios:1bd817d466458ae1d1d43e',
    messagingSenderId: '762160532123',
    projectId: 'livegreen-bf838',
    storageBucket: 'livegreen-bf838.firebasestorage.app',
    iosClientId: '762160532123-dtu762qporvdaf06gejfkf628rhfiuel.apps.googleusercontent.com',
    iosBundleId: 'com.example.livegreen',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVP58lYJzfnjFGE-RKdSkrGgNJ3oMUncI',
    appId: '1:762160532123:web:AIzaSyBe2f6a3i98n2b-ieMO97lW1oX69bQL2kQ',
    messagingSenderId: '762160532123',
    projectId: 'livegreen-bf838',
    authDomain: 'livegreen-bf838.firebaseapp.com',
    storageBucket: 'livegreen-bf838.firebasestorage.app',
    measurementId: 'G-BSG1S3GW3L',
  );
}